services:
  database:
    image: postgres:16
    container_name: database
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  
  server:
    build:
      context: ./server
    container_name: server
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
    depends_on:
      - database
    environment:
      DATABASE_URL: postgresql://postgres:postgres@database:5432/database

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    working_dir: /app
